<?xml version="1.0" encoding="utf-8"?><Database Name="aspnet-Chapter9-20120605204805" Class="StateDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDb)\v11.0;AttachDbFilename=|DataDirectory|\aspnet-Chapter9-20120605204805.mdf;Initial Catalog=aspnet-Chapter9-20120605204805;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="aspnet_Chapter9_20120605204805ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.State" Member="States">
    <Type Name="State">
      <Column Name="StateCode" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StateName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Path" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>